name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  # 1. SonarQube Quality Scan
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  # 2. Build and Push Docker Image
  build-and-push:
    needs: sonar-scan # Only runs if scan passes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: hello-world-pipeline
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  # 3. Trivy Container Vulnerability Scan
  trivy-scan:
    needs: build-and-push # Runs after image is pushed
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '110015905621.dkr.ecr.us-east-2.amazonaws.com/hello-world-pipeline:latest'
          format: 'table'
          exit-code: '1' # Fails the pipeline if CRITICAL/HIGH vulnerabilities exist
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
